global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'workstations'
    # This allows you to add/remove workstations in targets.json 
    # without restarting the Prometheus container!
    file_sd_configs:
      - files:
        - '/etc/prometheus/targets.json'
        refresh_interval: 30s
    relabel_configs:
      - source_labels: [job]
        regex: process_metrics
        action: drop

  - job_name: 'process_metrics'
    scrape_interval: 30s
    scrape_timeout: 25s
    file_sd_configs:
      - files:
        - '/etc/prometheus/targets.json'
        refresh_interval: 30s
    relabel_configs:
      - source_labels: [job]
        regex: process_metrics
        action: keep
