- name: Install Visual Studio Code
  become: true
  block:
    - name: Import Microsoft GPG key
      ansible.builtin.rpm_key:
        state: present
        key: https://packages.microsoft.com/keys/microsoft.asc

    - name: Add Visual Studio Code repository
      ansible.builtin.yum_repository:
        name: code
        description: Visual Studio Code
        baseurl: https://packages.microsoft.com/yumrepos/vscode
        enabled: true
        gpgcheck: true
        gpgkey: https://packages.microsoft.com/keys/microsoft.asc

    - name: Install Visual Studio Code
      ansible.builtin.dnf:
        name: code
        state: present
        update_cache: true
