---
- name: Restart Docker
  become: true
  ansible.builtin.systemd:
    name: docker
    state: restarted

- name: Restart containerd
  become: true
  ansible.builtin.systemd:
    name: containerd
    state: restarted
