{
 "title": "process-exporter-dashboard",
 "description": "Dashboard for monitoring Linux processes.",
 "tags": [
  "process-exporter",
  "linux",
  "monitoring"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "data_source", "query": "prometheus" },
   {
    "name": "server",
    "query": {
     "query": "label_values(process_exporter_build_info{job=\"$job\"},instance)"
    }
   },
   {
    "name": "port",
    "query": {
     "query": "label_values(process_exporter_build_info,instance)"
    }
   },
   {
    "name": "host",
    "query": {
     "query": "query_result(\"$server:$port\")"
    }
   },
   {
    "name": "job",
    "query": {
     "query": "label_values(process_exporter_build_info,job)"
    }
   },
   { "name": "port_node_exporter", "query": "9100" },
   { "name": "job_node_exporter", "label": "Node Exporter Job", "query": "server_metrics" },
   { "name": "topN", "label": "Top N", "query": "5,10,15,20" },
   {
    "name": "groupname",
    "label": "Process Group",
    "query": {
     "query": "label_values(namedprocess_namegroup_num_procs{instance=~\"$host\", job=\"$job\"}, groupname)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total Process Groups",
   "type": "stat",
   "description": "Number of named process groups currently being monitored.",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(namedprocess_namegroup_num_procs{instance=~\"$host\", groupname=~\"$groupname\", job=\"$job\"})"
    }
   ]
  },
  {
   "title": "Total Processes",
   "type": "stat",
   "description": "Total number of individual processes across all groups.",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(namedprocess_namegroup_num_procs{instance=~\"$host\", groupname=~\"$groupname\", job=\"$job\"})"
    }
   ]
  },
  {
   "title": "Total CPU (millicores)",
   "type": "stat",
   "description": "Aggregate CPU usage across all monitored process groups.",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(namedprocess_namegroup_cpu_seconds_total{instance=~\"$host\", groupname=~\"$groupname\", job=\"$job\"}[$__rate_interval])) * 1000"
    }
   ]
  },
  {
   "title": "Total Resident Memory",
   "type": "stat",
   "description": "Aggregate resident memory across all monitored process groups.",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(namedprocess_namegroup_memory_bytes{instance=~\"$host\", groupname=~\"$groupname\", memtype=\"resident\", job=\"$job\"})"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "CPU %",
   "type": "timeseries",
   "description": "CPU utilization (%) by process.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "topk($topN, (sum(irate(namedprocess_namegroup_cpu_seconds_total{instance=~\"$host\", groupname=~\"$groupname\", job=\"$job\"}[$__rate_interval])) by (groupname) > 0) / scalar(count(count(node_cpu_seconds_total{instance=\"$server:$port_node_exporter\", job=\"$job_node_exporter\"}) by (cpu))))",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "CPU (millicore)",
   "type": "timeseries",
   "description": "CPU utilization (millicore) by process.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "topk($topN, (sum(irate(namedprocess_namegroup_cpu_seconds_total{instance=~\"$host\", groupname=~\"$groupname\", job=\"$job\"}[$__rate_interval])) by (groupname) > 0) * 1000)",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Resident Memory % of RAM",
   "type": "timeseries",
   "description": "Resident memory as a percentage of total system RAM, per process group.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "topk($topN, namedprocess_namegroup_memory_bytes{instance=~\"$host\", groupname=~\"$groupname\", memtype=\"resident\", job=\"$job\"} / ignoring(memtype) namedprocess_namegroup_num_procs / scalar(node_memory_MemTotal_bytes{instance=\"$server:$port_node_exporter\", job=\"$job_node_exporter\"}))",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "Resident Memory",
   "type": "timeseries",
   "description": "Actual memory usage by process.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk($topN, namedprocess_namegroup_memory_bytes{instance=~\"$host\", groupname=~\"$groupname\", memtype=\"resident\", job=\"$job\"} / ignoring(memtype) namedprocess_namegroup_num_procs > 0)",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "Number Threads",
   "type": "timeseries",
   "description": "Number of threads.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "topk($topN, namedprocess_namegroup_num_threads{instance=~\"$host\", groupname=~\"$groupname\", job=\"$job\"})",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "Virtual Memory",
   "type": "timeseries",
   "description": "Total amount of memory that may be required by the process.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk($topN, namedprocess_namegroup_memory_bytes{instance=~\"$host\", groupname=~\"$groupname\", memtype=\"virtual\", job=\"$job\"} / ignoring(memtype) namedprocess_namegroup_num_procs > 0)",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "Context Switches",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "Voluntary Context Switches",
     "type": "timeseries",
     "description": "Voluntary context switch.  \nOccurs when a thread writes to IO or requests a resource that is unavailable.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "topk($topN, rate(namedprocess_namegroup_context_switches_total{instance=~\"$host\", groupname=~\"$groupname\", ctxswitchtype=\"voluntary\", job=\"$job\"}[$__rate_interval]))",
       "legendFormat": "{{groupname}}"
      }
     ]
    },
    {
     "title": "Nonvoluntary Context Switches",
     "type": "timeseries",
     "description": "Involuntary context switch.  \nOccurs when a thread exceeds the time interval assigned by the scheduler.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "topk($topN, rate(namedprocess_namegroup_context_switches_total{instance=~\"$host\", groupname=~\"$groupname\", ctxswitchtype=\"nonvoluntary\", job=\"$job\"}[$__rate_interval]))",
       "legendFormat": "{{groupname}}"
      }
     ]
    }
   ]
  },
  {
   "title": "File Descriptors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "Group File Descriptors",
     "type": "timeseries",
     "description": "Number of open file descriptors for the group.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "topk($topN, namedprocess_namegroup_open_filedesc{instance=~\"$host\", groupname=~\"$groupname\", job=\"$job\"})",
       "legendFormat": "{{groupname}}"
      }
     ]
    },
    {
     "title": "Total File Descriptors",
     "type": "timeseries",
     "description": "USED - Number of open file descriptors.  \nMAX - Maximum number of open file descriptors.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "process_open_fds{instance=~\"$host\", job=\"$job\"}",
       "legendFormat": "USED"
      },
      {
       "expr": "process_max_fds{instance=~\"$host\", job=\"$job\"}",
       "legendFormat": "MAX"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory Pressure",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "collapsed": true,
   "panels": [
    {
     "title": "Minor Page Faults",
     "type": "timeseries",
     "description": "Minor memory page faults.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "topk($topN, rate(namedprocess_namegroup_minor_page_faults_total{instance=~\"$host\", groupname=~\"$groupname\", job=\"$job\"}[$__rate_interval]))",
       "legendFormat": "{{groupname}}"
      }
     ]
    },
    {
     "title": "Major Page Faults",
     "type": "timeseries",
     "description": "Major memory page faults.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "topk($topN, rate(namedprocess_namegroup_major_page_faults_total{instance=~\"$host\", groupname=~\"$groupname\", job=\"$job\"}[$__rate_interval]))",
       "legendFormat": "{{groupname}}"
      }
     ]
    }
   ]
  },
  { "title": "Process Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Number Processes",
   "type": "timeseries",
   "description": "Number of processes in the group.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "topk($topN, namedprocess_namegroup_num_procs{instance=~\"$host\", groupname=~\"$groupname\", job=\"$job\"})",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "Processes Uptime",
   "type": "table",
   "description": "Process groups - Start time - Uptime.",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "time() - (namedprocess_namegroup_oldest_start_time_seconds{instance=~\"$host\", groupname=~\"$groupname\", job=\"$job\"} > 0)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}